name: Release

permissions: read-all

# description: |
#   Build a github release on pushed tag, after tests are completed.
#
#   The only available asset is a release note.

on:
  workflow_run:
    workflows:
      - "go test"
    types:
      - completed
    tags:
      - 'v*'

jobs:
  on-success:
    name: Ensure triggering workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The triggering workflow was successful"

  on-failure:
    name: Triggering workflow was unsuccessful
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The triggering workflow failed. Stopping here"
          exit 1

  gh-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: "Checkout code"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      -
        name: Create github release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          generate_release_notes: true # use github API to generate release notes
